name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: "3.12"
      run_tests: true

  docker:
    needs: build-test
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: day48-app
      tag: latest
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read

    steps:
      - name: Deploy application
        run: |
          echo "Deploying image: ${{ needs.docker.outputs.image_url }} to production"
          echo "Deployment completed successfully."